### ISSUE TITLE
Error when inserting prior-existing ConcreteNode

### ISSUE THREAD

**Issue by C7C8** [CS3733-TeamAlpha/Project#8]
When a prior-existing ConcreteNode is inserted into the database using the DatabaseController.insertNode() function, the following error is generated: 

> Provider table already exists
> Floor table already exists
> Node table already exists
> Office table already exists
> Neighbor table already exists
> org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: INSERT on table 'NODE' caused a violation of foreign key constraint 'SQL170206084352641' for key (3).  The statement has been rolled back.
> 	
> Caused by: ERROR 23503: INSERT on table 'NODE' caused a violation of foreign key constraint 'SQL170206084352641' for key (3).  The statement has been rolled back.
> 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
> 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
> 	... [lots] more
> org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: INSERT on table 'NODE' caused a violation of foreign key constraint 'SQL170206084352641' for key (3).  The statement has been rolled back.
> 	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
> 	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
> 	
> 	at integration.DatabasePathfindingTest.testLinkPersistance(DatabasePathfindingTest.java:49
> 
> Process finished with exit code 255

The code that generated the test may be found in src/test/java/integration/DatabasePathfindingTest.java:49. Maybe I'm just not databasing quite right? Hence the question tag.

**Comment by solashirai** [comment]
The code inserting a default floor appears to have accidentally been removed or not properly pushed into here. 
Pretty sure the cause of this error is that the node is trying to set it's floorID to 3 (hence error caused by key(3)) but the floor with ID 3 hasn't been inserted into the table. 
I've added an insertfloor(3, "defaultfloor", 3) call in DatabaseController's static{}. This should make this error go away, unless testing is doing something where static{...} isn't being called.

This is a bandaid fix. works for now, TODO will be to properly handle this SQL exception
